name: pgai
services:
  db:
    build:
      context: ../../../../extension
      dockerfile: Dockerfile
      target: pgai-test-db
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
  data: