[project]
name = "pgai-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "questionary",
  "jinja2",
  "yaspin",
  "psycopg[binary]",
]

[tool.uv.sources]
questionary = { git = "https://github.com/JamesGuthrie/questionary", branch = "fix-select-dynamic-choice" }
