name: pgai
services:
  db:
    build:
      context: ../extension
      dockerfile: Dockerfile
      target: pgai-test-db
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - path: ./.env
        required: false
      - path: ./db.env
        required: false
  pgai-installer:
    build: .
    depends_on:
      - db
    entrypoint: sh
    command:
      - -c
      - |
        for i in $(seq 1 10); do
          echo "Attempt $$i: installing pgai..."
          # always overwriting previous installation here.
          python -m pgai install -d postgres://postgres:postgres@db:5432/postgres && exit 0
          echo "Failed. Retrying in 1s..."
          sleep 1
        done
        echo "❌ pgai install failed after 10 attempts."
        exit 1
  vectorizer-worker:
    build: .
    depends_on:
      - pgai-installer
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
    env_file:
      - path: ./.env
        required: false
      - path: ./worker.env
        required: false
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
volumes:
  data:
