name: pgai
services:
  bot:
    build:
      dockerfile: Dockerfile
      context: .
      additional_contexts:
        docs: ../../docs
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db/postgres
      DOCS_PATH: /app/docs
    volumes:
      - ../../docs:/app/docs
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      POSTGRES_PASSWORD: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5432:5432"
    volumes:
      - data:/home/postgres/pgdata/data
  vectorizer-worker:
    image: timescale/pgai-vectorizer-worker:latest
    environment:
      PGAI_VECTORIZER_WORKER_DB_URL: postgres://postgres:postgres@db:5432/postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    command: [ "--poll-interval", "5s", "--log-level", "DEBUG" ]
volumes:
  data:
