create index on wiki_orig (wiki_id, paragraph_id);

create table wiki
( id bigint not null primary key generated by default as identity
, title text not null
, body text not null
, wiki_id int not null
, url text not null
);

create table queue (wiki_id int not null primary key);

insert into queue (wiki_id) select distinct wiki_id from wiki_orig;

do language plpgsql $$
declare
    _wiki_id int;
begin
    loop

        select wiki_id into _wiki_id
        from queue
        for update skip locked
        limit 1
        ;
        exit when not found;

        insert into wiki (title, body, wiki_id, url)
        select
          title
        , string_agg("text", E'\n\n' order by paragraph_id)
        , wiki_id
        , url
        from wiki_orig
        where wiki_id = _wiki_id
        group by wiki_id, title, url
        ;

        delete from queue 
        where wiki_id = _wiki_id
        ;
        commit;
    end loop;
end
$$;

