

create table ai.vectorizer_config
( id int not null primary key generated by default as identity
, source_schema name not null
, source_table name not null
, target_schema name not null
, target_table name not null
, target_column name not null
, queue_schema name not null
, queue_table name not null
, config jsonb not null
, unique (target_schema, target_table)
);
perform pg_catalog.pg_extension_config_dump('ai.vectorizer_config'::pg_catalog.regclass, '');


create table ai.vectorizer_execution
( id bigint not null primary key generated by default as identity
, config_id int not null
, config jsonb not null
, created timestamptz not null default now()
);
perform pg_catalog.pg_extension_config_dump('ai.vectorizer_execution'::pg_catalog.regclass, '');
