
create table @extschema@.vectorize_job
( id int not null primary key generated by default as identity
, source_schema name not null
, source_table name not null
, source_cols name[] not null
, target_schema name not null
, target_table name not null
, target_col name not null
, config jsonb
);


